# Generated by Django 5.2.5 on 2025-09-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_gen_api', '0004_snippet_remove_customuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
